window.google||(google={});window.google.update||(google.update={});google.update.c=[];function _GU_OnloadHandlerAdd(a,b){var c=google.update.c.length;"number"==typeof b&&b<c&&0<=b&&(c=b);google.update.c.splice(c,0,a)}function _GU_OnloadBody(a){var b=window.google.update.c;if(b)for(var c=0;c<b.length;++c)try{b[c](a)}catch(d){}}
function _GU_getPlatform(){if(window.google.update.f)return window.google.update.f;window.google.update.f="Win32"==navigator.platform?"win":"WinCE"==navigator.platform?"wince":/linux/i.test(navigator.platform)?"linux":/mac/i.test(navigator.platform)?"mac":"win";return window.google.update.f}
function _GU_getBrowserId(){if(window.google.update.a)return window.google.update.a;window.google.update.a=0;-1!=navigator.userAgent.indexOf("Opera/")?window.google.update.a=0:-1!=navigator.userAgent.indexOf(" Firefox/")?window.google.update.a=3:-1!=navigator.userAgent.indexOf("MSIE")||-1!=navigator.userAgent.indexOf(" Trident/")?-1!=navigator.userAgent.indexOf("Windows CE")?window.google.update.a=0:-1==navigator.userAgent.indexOf("PPC")&&-1==navigator.userAgent.indexOf("Smartphone")&&(window.google.update.a=
2):-1!=navigator.userAgent.indexOf(" Edge/")?window.google.update.a=5:-1!=navigator.userAgent.indexOf(" Chrome/")?window.google.update.a=4:-1!=navigator.userAgent.indexOf(" Safari/")&&(window.google.update.a=0);return window.google.update.a}function _GU_setCookie(a,b,c){a=a+"="+escape(b);-1!=c&&(b=new Date,b.setMinutes(b.getMinutes()+c),a+=";expires="+b.toUTCString());document.cookie=a}function _GU_setSessionCookie(a,b){_GU_setCookie(a,b,-1)}
function _GU_getCookie(a){if(document.cookie){var b=document.cookie.indexOf(a+"=");if(-1!=b&&(0==b||";"==document.cookie.substring(b-2,b-1)))return b=b+a.length+1,a=document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),unescape(document.cookie.substring(b,a))}return""}function _GU_removeCookie(a){_GU_setCookie(a,"",0)}function _GU_areCookiesSupported(){_GU_setCookie("test","1",1);var a="1"==_GU_getCookie("test");_GU_removeCookie("test");return a}
function _GU_initIid(){function a(){function c(){var d=Math.floor(65536*Math.random());for(d=d.toString(16);4>d.length;)d="0"+d;return d.toUpperCase()}return"{"+c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c()+"}"}var b=_GU_getCookie("iid");b?window.google.update.b=b:_GU_areCookiesSupported()?(window.google.update.b=a(),_GU_setSessionCookie("iid",window.google.update.b)):window.google.update.b="{11112222-3333-4444-5555-666677778888}"}
function _GU_getIid(){window.google.update.b||_GU_initIid();return window.google.update.b}function _GU_experimentTripletToTagValue(a){if("string"!=typeof a)return"";a=a.split(",");if(3!=a.length)return"";var b=Number(a[2]);return b?(b*=864E5,b=(new Date((new Date).getTime()+b)).toUTCString(),encodeURIComponent(a[0]+"="+a[1]+"|"+b)):""}
function _GU_experimentTripletArrayToTagElement(a,b){if(!a)return"";var c="";try{b=b?"omahaexperiments":"experiments";for(var d=[],e=0;e<a.length;++e){var f=_GU_experimentTripletToTagValue(a[e]);f&&d.push(f)}d.length&&(c="&"+b+"="+d.join(encodeURIComponent(";")))}catch(g){}return c}function _GU_createAppInfo(a,b,c,d,e){var f={};f.guid=a;f.name=b;f.needsAdmin=c;a=e?_GU_experimentTripletArrayToTagElement(e):"";f.customParams=(d||"")+a;return f}
function GU_BuildTag(a,b){b||(b="");for(var c="",d=0;d<a.length;++d)0==d?(c+="appguid="+a[d].guid,c+=b):c+="&appguid="+a[d].guid,c+="&appname="+encodeURIComponent(a[d].name).replace(/~/g,"%7E").replace(/!/g,"%21").replace(/\*/g,"%2A").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/'/g,"%27"),c+="&needsadmin="+a[d].needsAdmin,a[d].customParams&&(c+=a[d].customParams);return c}
function GU_buildGlobalExtra(a,b,c){a="&iid="+_GU_getIid()+"&lang="+a+"&browser="+_GU_getBrowserId()+"&usagestats=";a=b?a+"1":a+"0";c&&(a+=_GU_experimentTripletArrayToTagElement(c,!0));return a}function _GU_isClickOnceAvailable(){return!1}function _GU_isOneClickAvailable(){return!1}function _GU_SetupOneClick(){}function _GU_SetupOneClickVersions(){}function _GU_buildDlPath(a,b,c,d,e,f){b=GU_buildGlobalExtra(b,c,f);a=GU_BuildTag(a,b);return d+"/tag/s/"+encodeURIComponent(a)+e}
function _GU_buildDlPathNoTag(a,b,c,d,e){return d+e}function _GU_buildClickOncePath(){return""}var _GU_buildGlobalExtra=GU_buildGlobalExtra,_GU_BuildTag=GU_BuildTag;
